### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [fordfischer/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by fordfischer** [comment]
I'm not 100% sure this is what you were talking about but I added the "viewport meta tag" to my <head> which http://getbootstrap.com/css/ is supposed "to ensure proper rendering and touch zooming":
  <meta name="viewport" content="width=device-width, initial-scale=1">

I didn't play around with it on mobile a lot before submitting it, so it's not clear to me if the experience is a lot better now.

**Comment by kenmazaika** [comment]
Perfect!  That change will make it look much nicer on mobile devices!
